name: Player selection snapshots

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *" # 4AM AEST every day
  # push:
  #   branches:
  #     - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true


    - name: Install dependencies
      run: install.packages(c("dplyr", "purrr", "httr", "arrow", "tidyr"))
      shell: Rscript {0}


    - name: Run Script
      run: |
        source("afl_fantasy/player_selection_snapshots.R", echo = TRUE)
      shell: Rscript {0}
      
    - name: Commit
      run: |
        git config --global user.name 'bit in that'
        git config --global user.email 'timothy.gummer@gmail.com'
        git add .
        git pull
        git commit -m 'ACTION: get player selection snapshot' || echo "No changes to commit"
        git pull
        git push 
