name: AFLW Fantasy Selections (team_announcement)

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: "28 8 * * 4" # 6:28 PM every thursday (teams are announced at ~ 6:30)

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true


    - name: Install dependencies
      run: install.packages(c("here", "httr", "purrr", "dplyr", "tidyr", "arrow", "jsonlite"))
      shell: Rscript {0}


    - name: Run Script
      run: |
        source("aflw_fantasy/modules/get_player_data_afw.R", echo = TRUE)
        save_player_selections_teams()
      shell: Rscript {0}
      
    - name: Commit
      run: |
        git config --global user.name 'bit in that'
        git config --global user.email 'timothy.gummer@gmail.com'
        git add .
        git pull
        git commit -m 'ACTION: update aflw selections' || echo "No changes to commit"
        git pull
        git push
