name: AFLW Fantasy Rankings

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: "0 2 * * 1" # 12PM every monday
  # push:
  #   branches:
  #     - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: get libcurl
      run: |
        sudo apt-get install libcurl4-openssl-dev

    - name: Install dependencies
      run: install.packages(c("here", "httr", "dplyr", "arrow", "data.table"))
      shell: Rscript {0}


    - name: Run Script
      run: |
        source("aflw_fantasy/modules/get_rank_data_afw.R", echo = TRUE)
        source("aflw_fantasy/modules/get_content_creator_ranks.R", echo = TRUE)
        source("aflw_fantasy/modules/get_afw_session_id.R")
        session_id <- get_afw_session_id()
        save_ranking_data(session_id)
        save_content_creator_ranks()
      shell: Rscript {0}
      
    - name: Commit
      run: |
        git config --global user.name 'bit in that'
        git config --global user.email 'timothy.gummer@gmail.com'
        git add .
        git pull
        git commit -m 'ACTION: update aflw ranks' || echo "No changes to commit"
        git pull
        git push 
