name: AFLW Fantasy Top Lineups

on: 
  workflow_dispatch:
  # schedule:
  #   - cron: "30 2 * * 1" # 12:30PM every monday
  # push:
  #   branches:
  #     - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true


    - name: Install dependencies
      run: install.packages(c("here", "httr", "purrr", "dplyr", "tidyr", "arrow", "xml2", "jsonlite"))
      shell: Rscript {0}


    - name: Run Script
      run: |
        source("aflw_fantasy/modules/get_lineup_data_afw.R", echo = TRUE)
        save_top_10000_lineups("533aac36e90c0ae896cb3a89_1696920884")
      shell: Rscript {0}
      
    - name: Commit
      run: |
        git config --global user.name 'bit in that'
        git config --global user.email 'timothy.gummer@gmail.com'
        git add .
        git pull
        git commit -m 'ACTION: update aflw top lineups' || echo "No changes to commit"
        git pull
        git push
