name: All player stats

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true


    - name: Install dependencies
      run: install.packages(c("httr", "arrow", "tidyr", "dplyr", "purrr", "stringr"))
      shell: Rscript {0}

    - name: Run Script
      run: |
        source("players/get_player_stats.R", echo = TRUE)
      shell: Rscript {0}
      
    - name: Commit
      run: |
        git config --global user.name 'bit in that'
        git config --global user.email 'timothy.gummer@gmail.com'
        git add .
        git pull
        git commit -m 'ACTION: get all player stats' || echo "No changes to commit"
        git pull
        git push 
