name: bolter player ownership snapshots

on: 
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *" # every hour for now
    # - cron: "0 17 * * *" # change it to 4AM AEST every day afterwards
  # push:
  #   branches:
  #     - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true


    - name: Install dependencies
      run: install.packages(c("dplyr", "httr2", "arrow", "jsonlite"))
      shell: Rscript {0}


    - name: Run Script
      run: |
        source("bolter/bolter_player_ownership_processing.R", echo = TRUE)
        source("bolter/bolter_player_ownership_snapshots.R", echo = TRUE)
      shell: Rscript {0}
      
    - name: Commit
      run: |
        git config --global user.name 'bit in that'
        git config --global user.email 'timothy.gummer@gmail.com'
        git add .
        git pull
        git commit -m 'ACTION: get bolter ownership snapshot' || echo "No changes to commit"
        git pull
        git push 
