name: test that scheduler runs

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "55 6 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
