name: Test

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install here
      run: install.packages("here")
      shell: Rscript {0}

    - name: Install httr
      run: install.packages("httr")
      shell: Rscript {0}

    - name: Install dplyr
      run: install.packages("dplyr")
      shell: Rscript {0}

    - name: Install arrow
      run: install.packages("arrow")
      shell: Rscript {0}

    - name: Install data.table
      run: install.packages("data.table")
      shell: Rscript {0}

    - name: Install jsonlite
      run: install.packages("jsonlite")
      shell: Rscript {0}

    - name: Install purrr
      run: install.packages("purrr")
      shell: Rscript {0}

    - name: Install tidyr
      run: install.packages("tidyr")
      shell: Rscript {0}

    - name: Install all dependencies
      run: install.packages(c("here", "httr", "purrr", "dplyr", "tidyr", "arrow", "jsonlite", "data.table")
      shell: Rscript {0}
      