name: test R code runs

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Install Dependencies
      run: Rscript -e 'install.packages(c("here"))'
    - name: Run Script
        run: Rscript -e 'source(here::here("R", "test.R"), echo = TRUE)'
    
